Erikas_HomeMade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from usuarios import views as viewsUsuarios

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    # path('hello/', viewsUsuarios.hello),
    path('configuracion/', include('usuarios.urls')),
    path('reservas/', include('reservas.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('ventas/', include('ventas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalogo/', views.catalogo_productos, name='catalogo'),
]

reservas/urls.py
from django.contrib import admin
from django.urls import path
from . import views as viewsReservas
app_name = 'reservas'

urlpatterns = [
    path('hello/', viewsReservas.hello),
    path('listar_reservas/', viewsReservas.listar_reservas, name='listar_reserva'),
    path('crear_reserva/', viewsReservas.crear_reserva, name='crear_reserva'),
    # path('editar/<int:id_reserva>/', viewsReservas.editar_reserva, name='editar_reserva'),
    path('editar/', viewsReservas.editar_reserva, name='editar_reserva'),
    # path('eliminar/<int:id_reserva>/', viewsReservas.eliminar_reserva, name='eliminar_reserva'),
    path('eliminar/', viewsReservas.eliminar_reserva, name='eliminar_reserva'),
    path('listar_reservas_cliente/', viewsReservas.listar_reservas_cliente, name='listar_reserva_cliente'),
    path('cambiar_estado_reserva/', viewsReservas.cambiar_estado_reserva, name='cambiar_estado_reserva'),
    path('cambiar_fecha_reserva/', viewsReservas.cambiar_fecha_reserva, name='cambiar_fecha_reserva'),

]

usuarios/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views as viewsUsuarios
app_name = 'usuarios'

urlpatterns = [
    path('hello/', viewsUsuarios.hello),
    # PERMISOS
    path('listar_permisos/', viewsUsuarios.listar_permisos, name='listar_permisos'),
    path('crear_permiso/', viewsUsuarios.crear_permiso, name='crear_permiso'),
    path('editar_permiso/<int:id_permiso>/', viewsUsuarios.editar_permiso, name='editar_permiso'),
    path('editar_permiso/', viewsUsuarios.editar_permiso, name='editar_permiso'),
    path('cambiar_estado_permiso/', viewsUsuarios.cambiar_estado_permiso, name='cambiar_estado_permiso'),
    path('eliminar_permiso/<int:id_permiso>/', viewsUsuarios.eliminar_permiso, name='eliminar_permiso'),

    # ROLES
    path('listar_roles/', viewsUsuarios.listar_roles, name='listar_roles'),
    path('crear_rol/', viewsUsuarios.crear_rol, name='crear_rol'),
    path('editar_rol/<int:id_rol>/', viewsUsuarios.editar_rol, name='editar_rol'),
    path('editar_rol/', viewsUsuarios.editar_rol, name='editar_rol'),
    path('cambiar_estado_rol/', viewsUsuarios.cambiar_estado_rol, name='cambiar_estado_rol'),
    path('eliminar_rol/<int:id_rol>/', viewsUsuarios.eliminar_rol, name='eliminar_rol'),
    # path('eliminar_rol/', viewsUsuarios.eliminar_rol, name='eliminar_rol'),

    # USUARIOS
    path('listar_usuarios/', viewsUsuarios.listar_usuarios, name='listar_usuarios'),
    path('crear_usuario/', viewsUsuarios.crear_usuario, name='crear_usuario'),
    path('cambiar_rol/', viewsUsuarios.cambiar_rol, name='cambiar_rol'),
    path('cambiar_estado/', viewsUsuarios.cambiar_estado, name='cambiar_estado'),
    path('editar_usuario/', viewsUsuarios.editar_usuario, name='editar_usuario'),
    path('editar_usuario_/<int:id_usuario>/', viewsUsuarios.editar_usuario_, name='editar_usuario_'),
    path('eliminar_usuario/', viewsUsuarios.eliminar_usuario, name='eliminar_usuario'),
    path('eliminar_usuario/<int:id_usuario>/', viewsUsuarios.eliminar_usuario, name='eliminar_usuario'),

    path('iniciar_sesion/', viewsUsuarios.iniciar_sesion, name='login'),
    path('registrarse/', viewsUsuarios.registrarse, name='register'),
    path('editar_perfil/', viewsUsuarios.editar_account, name='editar_account'),
    path('editar_contraseña/', viewsUsuarios.editar_contraseña, name='editar_contraseña'),
    path('cerrar_sesion/', viewsUsuarios.cerrar_sesion, name='logout'),
    path('requestLogin/', viewsUsuarios.requestLogin, name='requestLogin'),
    path('recuperar Contraseña/', viewsUsuarios.forgotPassword, name='forgotPassword'),
    path('editar_foto_perfil/', viewsUsuarios.editar_foto_perfil, name='editar_foto_perfil'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservas/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from usuarios.models import Usuario  # Importa el modelo de usuarios

def validate_fecha_hoy(value):
    if value.date() != timezone.now().date():
        raise ValidationError('La fecha debe ser la del día de hoy')

class Reserva(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=timezone.now)
    fecha_cita = models.DateTimeField()
    descripcion = models.CharField(max_length=255, null=True, blank=True)
    estado = models.CharField(max_length=80, default="Pendiente")

    def __str__(self):
        return f"Reserva {self.id}"

    def clean(self):
        if self.fecha_cita < self.fecha:
            raise ValidationError(_("La fecha de la cita no puede ser anterior a la fecha de la reserva."))

    class Meta:
        db_table = 'reservas'

reservas/forms.py
from django import forms
from .models import Reserva
from django.utils import timezone
from datetime import datetime

class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['usuario', 'fecha_cita', 'descripcion']
        widgets = {
            'usuario': forms.Select(attrs={'class': 'form-control'}),
            'fecha_cita': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            self.fields['fecha'].widget = forms.HiddenInput()
            # Opcionalmente, si deseas mostrar la fecha de reserva pero sin ser editable:
            # self.fields['fecha'].widget.attrs['readonly'] = True

        
class ReservaFormIndex(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['usuario', 'fecha_cita', 'descripcion']
        widgets = {
            'fecha_cita': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-input', 'placeholder': 'Fecha'}),
            'usuario': forms.Select(attrs={'class': 'form-input', 'placeholder': 'Usuario'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-input textarea-lg', 'placeholder': 'Descripción'}),
        }

    def clean_fecha_cita(self):
        fecha_cita = self.cleaned_data.get('fecha_cita')
        if fecha_cita:
            hora_inicio = datetime.time(7, 0)
            hora_fin = datetime.time(20, 0)
            if not (hora_inicio <= fecha_cita.time() <= hora_fin):
                raise forms.ValidationError("La hora debe estar entre las 7:00 AM y las 8:00 PM.")
        return fecha_cita


class ReservaFormEditar(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['fecha_cita', 'descripcion', 'estado']
        widgets = {
            'estado': forms.Select(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completada', 'Completada')])
        }


        def clean_fecha_cita(self):
            fecha_cita = self.cleaned_data.get('fecha_cita')
            if fecha_cita < datetime.now().date():
                raise forms.ValidationError("La fecha de la cita no puede ser anterior a la fecha actual.")
            elif fecha_cita < self.instance.fecha.date():
                raise forms.ValidationError("La fecha de la cita no puede ser anterior a la fecha de la reserva actual.")
            return fecha_cita

        

        

reservas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Reserva
from .forms import *
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.hashers import make_password
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
import json
from django.contrib.auth.hashers import make_password  # Importa make_password
from django.views.decorators.http import require_http_methods
import requests
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import login as auth_login
from datetime import timedelta, datetime

# Create your views here.
def hello(request):
    return HttpResponse("Hello World")

def listar_reservas(request):
    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            
            reserva = form.save(commit=False)
            # Aquí puedes realizar cualquier procesamiento adicional antes de guardar el objeto
            reserva.save()
            return JsonResponse({'success': True})
        else:
            # Si el formulario no es válido, se envían los errores de validación
            errors = dict(form.errors.items())
            return JsonResponse({'success': False, 'message': 'Por favor ingrese la fecha valida (que sea dos dias a partir de hoy)', 'errors': errors})
    else:
        reservas = Reserva.objects.all()
        form = ReservaForm()
        return render(request, 'listar_reservas.html', {'reservas': reservas, 'form': form})  

def crear_reserva(request):
    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            reserva = form.save(commit=False)
            fecha_cita = reserva.fecha_cita

            # Redondear la hora al intervalo de media hora más cercano
            minuto = fecha_cita.minute
            if minuto >= 30:
                fecha_cita = fecha_cita.replace(minute=30, second=0, microsecond=0)
            else:
                fecha_cita = fecha_cita.replace(minute=0, second=0, microsecond=0)

            # Verificar si ya existe una reserva en el mismo día y hora
            reservas_existentes = Reserva.objects.filter(fecha_cita=fecha_cita)
            if reservas_existentes.exists():
                return JsonResponse({
                    'success': False,
                    'message': 'Ya existe una reserva para esa fecha y hora.'
                })

            # Guardar la reserva si no hay conflicto
            reserva.fecha_cita = fecha_cita
            reserva.save()
            return JsonResponse({'success': True})
        else:
            # Si el formulario no es válido, se envían los errores de validación
            errors = dict(form.errors.items())
            return JsonResponse({
                'success': False,
                'message': 'Por favor ingrese una fecha válida (que sea dos días a partir de hoy)',
                'errors': errors
            })
    else:
        form = ReservaForm()
    return render(request, 'crear_reserva.html', {'form': form})


@require_POST
def editar_reserva(request):
    print(request.POST)  # Imprimir el contenido de request.POST
    reserva_id = request.POST.get('Reserva_id')
    reserva = get_object_or_404(Reserva, pk=reserva_id)

    # Creamos una instancia del formulario con los datos recibidos y la instancia del usuario
    form = ReservaFormEditar(request.POST, instance=reserva)

    # Validamos el formulario
    if form.is_valid():
        # Guardamos los cambios en la reserva
        saved_instance = form.save()
        print(saved_instance)  # Esta línea imprime la instancia guardada en la consola
        return JsonResponse({'success': True})
    else:
        # Si el formulario no es válido, devolvemos una respuesta con los errores
        errors = dict(form.errors.items())
        return JsonResponse({'success': False, 'errors': errors})

def eliminar_reserva(request):
    if request.method == 'POST':
        reserva_id = request.POST.get('reserva_id')
        print("Usuario ID:", reserva_id)
        data = json.loads(request.body)
        reserva_id = data.get('reserva_id')
        print("Reserva ID:", reserva_id)
        try:
            reserva = Reserva.objects.get(pk=reserva_id)
            
            reserva.delete()
            return JsonResponse({'success': True})
        except Reserva.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'La reserva no existe'})
    else:
        return JsonResponse({'success': False, 'message': 'Método no permitido'})


def listar_reservas_cliente(request):
    if not request.session.get('usuario_id'):
        return JsonResponse({'success': False, 'message': 'Usuario no autenticado'}, status=401)

    usuario_id = request.session['usuario_id']

    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            reserva = form.save(commit=False)
            reserva.usuario_id = usuario_id  # Asigna el usuario a la reserva
            reserva.save()
            return JsonResponse({'success': True})
        else:
            errors = dict(form.errors.items())
            return JsonResponse({'success': False, 'message': 'Hubo un error de validación', 'errors': errors})
    else:
        reservas = Reserva.objects.filter(usuario_id=usuario_id)
        form = ReservaForm()
        return render(request, 'mis_reservas.html', {'reservas': reservas, 'form': form})
    

@csrf_exempt
def cambiar_estado_reserva(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        reserva_id = data.get('reserva_id')
        nuevo_estado = data.get('estado')
        
        print("ID de la reserva:", reserva_id)
        print("Nuevo estado:", nuevo_estado)

        reserva = Reserva.objects.get(pk=reserva_id)
        reserva.estado = nuevo_estado
        reserva.save()
        
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False})
    
@csrf_exempt
def cambiar_fecha_reserva(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        reserva_id = data.get('reserva_id')
        nueva_fecha = data.get('fecha_cita')
        
        try:
            reserva = Reserva.objects.get(pk=reserva_id)
            reserva.fecha_cita = nueva_fecha  # Actualiza la fecha de la cita
            reserva.save()
            
            return JsonResponse({'success': True})
        except Reserva.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Reserva no encontrada'})

    return JsonResponse({'success': False, 'message': 'Método no permitido'}, status=405)

reservas/templates/crear_reserva.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Reserva</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>

<body>
    <div class="container">
        <h1>Crear Nueva Reserva</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</body>

</html>
{% if not request.session.usuario_id %}
<script>
    window.location.href = "{% url 'usuarios:requestLogin' %}";

</script>
{% elif "Crear Reservas" not in request.session.permisos %}
<script>
    window.location.href = "{% url 'usuarios:requestLogin' %}";

</script>
{% endif %}

reservas/templates/editar_reserva.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Reserva</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>

<body>
    <div class="container">
        <h1>Editar Reserva</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>
</body>

</html>
{% if not request.session.usuario_id %}
<script>
    window.location.href = "{% url 'usuarios:requestLogin' %}";

</script>
{% elif "Editar Reservas" not in request.session.permisos %}
<script>
    window.location.href = "{% url 'usuarios:requestLogin' %}";

</script>
{% endif %}

reservas/templates/eliminar_reserva.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Reserva</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>

<body>
    <div class="container">
        <h1>¿Estás seguro que deseas eliminar la Reserva "{{ reserva.descripcion }}"?</h1>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirmar Eliminación</button>
        </form>
    </div>
</body>

</html>
{% if not request.session.usuario_id %}
<script>
    window.location.href = "{% url 'usuarios:requestLogin' %}";

</script>
{% elif "Eliminar Reservas" not in request.session.permisos %}
<script>
    window.location.href = "{% url 'usuarios:requestLogin' %}";

</script>
{% endif %}

reservas/templates/mis_reservas.html
{% extends 'layouts/navbar.html' %}
{% load static %}
{% block content %}
<!-- Estilos CSS -->
<link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}" />
<link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}" />
<link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}" />
<link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}" />
<link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.datatables.net/v/dt/dt-1.10.25/datatables.min.js"></script>
<script src="{% static 'js/reservas.js' %}"></script>
<style>
    .fecha-cita-button {
    cursor: pointer;
    background-color: #007bff;
    color: #fff;
    border: 1px solid #007bff;
    border-radius: 4px;
    padding: 8px 12px;
    text-align: center;
    transition: background-color 0.3s;
}

.fecha-cita-button:hover {
    background-color: #0056b3;
}

</style>
<!-- Contenido principal -->
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Mis Reservas</h4>
                <div class="table-responsive">
                    <table id="reservaTable" class="table table-hover row-border" style="width:100%">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Fecha Reserva</th>
                                <th>Descripción</th>
                                <th>Estado</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for reserva in reservas %}
                            <tr>
                                <td>{{ reserva.usuario.nombre }}</td>
                                <td>
                                    <label class="badge badge-primary hover-cursor {% if 'Editar Mis Reservas' in request.session.permisos %}badge-info editarfechacita{% endif %}" data-reserva-id="{{ reserva.id }}">{{ reserva.fecha_cita }}</label>
                                </td>
                                <td>{{ reserva.descripcion }}</td>
                                <td>
                                    <label 
                                        class="badge badge-outline-primary hover-cursor {% if 'Editar Mis Reservas' in request.session.permisos %}badge-outline-info change-estado{% endif %}" 
                                        data-reserva-id="{{ reserva.id }}"
                                        {% if reserva.estado == 'Completada' or reserva.estado == 'Cancelada' %}style="pointer-events: none; color: grey;"{% endif %}
                                    >
                                        {{ reserva.estado }}
                                    </label>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        if ($.fn.DataTable.isDataTable('#reservaTable')) {
            $('#reservaTable').DataTable().destroy();
        }

        var dataTableConfig = {
            "lengthChange": false,
            "pageLength": 5,
            "searching": true,
            "language": {
                "search": "Buscar:",
                "zeroRecords": "No se encontraron resultados",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando 0 a 0 de 0 registros",
                "infoFiltered": "(filtrados de _MAX_ registros en total)",
                "paginate": {
                    "first": "Primero",
                    "last": "Último",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            },
            "dom": '<"top"lf>rt<"bottom"ip>',
        };

        $('#reservaTable').DataTable(dataTableConfig);
        $("#reservaTable_filter").detach().appendTo(".top");

        // Mover el botón "Agregar" al lado del cuadro de búsqueda
        $(".top").append('<a type="button" class="btn btn-inverse-success btn-fw ml-2" href="{% url 'home:index' %}#CrearReserva">Crear</a>');

        $('#reservaTable').on('click', 'td .change-estado', function () {
            var reserva_id = $(this).data('reserva-id');
            var estado_actual = $(this).text().trim();

            // Verificar si el estado es "Completada" o "Cancelada"
            if (estado_actual === 'Completada' || estado_actual === 'Cancelada') {
                return;  // Salir de la función si no se permite la edición
            }

            console.log("ID de la reserva:", reserva_id);  // Imprime el ID de la reserva en la consola

            Swal.fire({
                title: '¿Estás seguro de cambiar estado?',
                html: '<h3>Esta opcion no es reversible</h3>'+' <input type="hidden" name="" id="estadoSelect" value="Cancelada">',
                icon: 'info',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Cambiar',
                preConfirm: () => {
                    var nuevoEstado = $('#estadoSelect').val();

                    return fetch("{% url 'reservas:cambiar_estado_reserva' %}", {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify({
                            'estado': nuevoEstado,
                            'reserva_id': reserva_id  // Añadir el ID de la reserva al cuerpo de la petición
                        }),
                    })
                    .then(response => {
                        if (!response.ok) {
                            throw new Error('Hubo un problema al cambiar el estado.');
                        }
                        return response.json();
                    })
                    .catch(error => {
                        Swal.showValidationMessage(`Request failed: ${error}`);
                    });
                },
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire('¡Estado cambiado!', 'El estado de la reserva se ha cambiado correctamente.', 'success').then(() => {
                        location.reload();
                    });
                }
            });
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('#reservaTable').on('click', 'td .editarfechacita', function () {
            var reserva_id = $(this).data('reserva-id');
            var fecha_cita = $(this).text().trim();

            // Crear el campo de fecha y hora con Flatpickr
            var flatpickrInput = $('<input>').attr({
                type: 'text',
                id: 'swal-input1',
                class: 'swal2-input',
            });

            // Mostrar la alerta de SweetAlert para editar la fecha y hora
            Swal.fire({
                title: 'Editar Fecha y Hora de Cita',
                html: flatpickrInput[0],
                showCancelButton: true,
                confirmButtonText: 'Guardar',
                cancelButtonText: 'Cancelar',
                allowOutsideClick: false,
                preConfirm: () => {
                    return flatpickrInput.val();
                },
                didOpen: () => {
                    // Inicializar Flatpickr en el campo de entrada
                    flatpickr(flatpickrInput[0], {
                        enableTime: true,
                        dateFormat: 'Y-m-d H:i', // Formato de fecha y hora
                    });
                }
            }).then((result) => {
                if (result.isConfirmed) {
                    // Obtener la nueva fecha y hora ingresada por el usuario
                    var nueva_fecha = flatpickrInput.val();

                    // Realizar la petición para actualizar la fecha y hora de la reserva
                    fetch("{% url 'reservas:cambiar_fecha_reserva' %}", {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify({
                            'fecha_cita': nueva_fecha,
                            'reserva_id': reserva_id
                        }),
                    })
                    .then(response => {
                        if (!response.ok) {
                            throw new Error('Hubo un problema al cambiar la fecha de la reserva.');
                        }
                        return response.json();
                    })
                    .then(data => {
                        if (data.success) {
                            // Mostrar una alerta de éxito
                            Swal.fire('¡Fecha y Hora cambiadas!', 'La fecha y hora de la reserva se han cambiado correctamente.', 'success').then(() => {
                                // Recargar la página o realizar alguna otra acción
                                location.reload();
                            });
                        } else {
                            // Mostrar una alerta de error si no se pudo cambiar la fecha y hora
                            Swal.fire('Error', 'Hubo un problema al cambiar la fecha y hora de la reserva. Por favor, inténtelo de nuevo más tarde.', 'error');
                        }
                    })
                    .catch(error => {
                        // Mostrar una alerta de error si hubo un problema con la petición
                        Swal.fire('Error', 'Hubo un problema al procesar su solicitud. Por favor, inténtelo de nuevo más tarde.', 'error');
                        console.error('Error:', error);
                    });
                }
            });
        });
    });
</script>






{% if not request.session.usuario_id %}
<script>
    window.location.href = "{% url 'usuarios:requestLogin' %}";
</script>
{% elif "Listar Mis Reservas" not in request.session.permisos %}
<script>
    window.location.href = "{% url 'usuarios:requestLogin' %}";
</script>
{% endif %}
{% endblock %}